name: RuboCop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2 # or your desired version
      - name: Set gem environment variables
        env:
          GEM_HOME: ${{ github.workspace }}/.gems
          GEM_PATH: ${{ github.workspace }}/.gems
        run: mkdir -p $GEM_HOME
      - name: Install missing gems
        run: bundle install rubocop
      - name: RuboCop Lint
        run: bundle exec rubocop
