name: RuboCop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2 # or your desired version
      - name: Update bundler
        run: gem update --system && gem install bundler
      - name: Add gem executable path to PATH
        run: echo "::add-path::$(ruby -e 'puts Gem.user_dir')/bin"
      - name: Install missing gems
        run: bundle install --jobs 4 --retry 3
      - name: RuboCop Lint
        run: bundle exec rubocop
